### ISSUE TITLE
datepicker and datetimepicker are required?

### ISSUE THREAD

**Issue by pablosalgadom** [kolodovskyy/simple_form_bootstrap3#4]
I want to know if the lines for the application.js and application.css which includes the "bootstrap-datepicker" and "bootstrap-datetimepicker" are mandatory to use the gem, because it seems to only add a pretty datetimepicker  to simple_form, but i am already using a jquery datetimepicker and i want to know if i will have no problem removing those lines. If this is not mandatory, i think that IMHO it should be mentioned in the readme instructions.

Thanks in advance :D

**Comment by kolodovskyy** [comment]
I think you can remove js and css inclusion. But date and datetime inputs maped to custom classes:

```ruby
map_type :datetime, to: SimpleForm::Inputs::DateTimePickerInput
map_type :date,     to: SimpleForm::Inputs::DatePickerInput
```

Maybe it will have some problems with you jquery picker, test it.
