### ISSUE TITLE
Input 100% width with label: false, horizontal_form_for

### ISSUE THREAD

**Issue by westonganger** [kolodovskyy/simple_form_bootstrap3#5]
I want to make some inputs have no label and appear with 100% width

The problem is that it generates columns for label and input

Is there a way to do this?

**Comment by kolodovskyy** [comment]
Use default form, it use block size for input

**Comment by westonganger** [comment]
Yeah but you can't nest form tags I want horizontal for some inputs and inline for other inputs

**Comment by kolodovskyy** [comment]
bootstrap not support mixed forms :)
